// Generated by CoffeeScript 1.4.0
(function() {

  define(["models/Creature", "Backbone"], function(CreatureModel) {
    var Creatures;
    Creatures = Backbone.Collection.extend({
      model: CreatureModel,
      initialize: function() {}
    });
    return new Creatures;
  });

}).call(this);
