// Generated by CoffeeScript 1.4.0
(function() {

  define(["models/ViewportTile", "Backbone"], function(ViewportTileModel) {
    var ViewportTiles;
    ViewportTiles = Backbone.Collection.extend({
      model: ViewportTileModel,
      initialize: function() {}
    });
    return new ViewportTiles;
  });

}).call(this);
