// Generated by CoffeeScript 1.4.0
(function() {

  define(["collections/Creatures", "models/Heightmap", "collections/MapTiles", "Backbone"], function(creatures, heightmapModel, mapTiles) {
    var Foreman;
    Foreman = Backbone.Model.extend({
      assignWorkerToSite: function(unemployedCreature, workSiteModel) {
        unemployedCreature.set("workSite", workSiteModel);
        return workSiteModel.set("worker", unemployedCreature);
      },
      findJob: function(unemployedCreature) {
        var availableJobs, path, workSiteModel;
        availableJobs = mapTiles.where({
          buildingType: 3,
          worker: void 0
        });
        if (availableJobs.length === 0) {
          return;
        }
        workSiteModel = availableJobs[0];
        path = unemployedCreature.findPath(workSiteModel);
        if (path.length === 0) {
          return;
        }
        return this.assignWorkerToSite(unemployedCreature, workSiteModel);
      },
      findWorker: function(workSiteModel) {
        var path, unemployedCreature, unemployedCreatures;
        unemployedCreatures = creatures.where({
          workSite: void 0
        });
        if (unemployedCreatures.length === 0) {
          return;
        }
        unemployedCreature = unemployedCreatures[0];
        path = unemployedCreature.findPath(workSiteModel);
        if (path.length === 0) {
          return;
        }
        return this.assignWorkerToSite(unemployedCreature, workSiteModel);
      }
    });
    return new Foreman;
  });

}).call(this);
