// Generated by CoffeeScript 1.4.0
(function() {

  define(["Backbone"], function() {
    var ViewportTile;
    return ViewportTile = Backbone.Model.extend({
      defaults: {
        roadType: 0
      }
    });
  });

}).call(this);
