// Generated by CoffeeScript 1.4.0
(function() {

  define(["Backbone"], function() {
    var ToolbarView;
    return ToolbarView = Backbone.View.extend({
      el: ".action-toolbar",
      activeContext: "move",
      events: {
        "click .btn": "onBtnClick",
        "click .move-btn": "onMoveBtnClick",
        "click .road-btn": "onRoadBtnClick",
        "click .home-btn": "onHomeBtnClick",
        "click .farm-btn": "onFarmBtnClick",
        "click .refinery-btn": "onRefineryBtnClick",
        "click .remove-btn": "onRemoveBtnClick"
      },
      initialize: function() {
        return $("." + this.activeContext + "-btn").addClass("active");
      },
      onBtnClick: function(jqEvent) {
        this.$(".btn.active").removeClass("active");
        return $(jqEvent.currentTarget).addClass("active");
      },
      onMoveBtnClick: function() {
        return this.activeContext = "move";
      },
      onRoadBtnClick: function() {
        return this.activeContext = "road";
      },
      onHomeBtnClick: function() {
        return this.activeContext = "home";
      },
      onFarmBtnClick: function() {
        return this.activeContext = "farm";
      },
      onRefineryBtnClick: function() {
        return this.activeContext = "refinery";
      },
      onRemoveBtnClick: function() {
        return this.activeContext = "remove";
      }
    });
  });

}).call(this);
