// Generated by CoffeeScript 1.4.0
(function() {

  define(["models/Heightmap", "Backbone"], function(heightmapModel) {
    var ViewportTile;
    return ViewportTile = Backbone.View.extend({
      tagName: "div",
      className: "map-tile",
      render: function() {
        this.calculateBackgroundPosition();
        this.setBackgroundPosition();
        return this;
      },
      setModel: function(model) {
        this.model = model;
        this.setListeners();
        return this.render();
      },
      clampX: function(x) {
        var width;
        width = heightmapModel.get("worldTileWidth");
        return (x + width) % width;
      },
      clampY: function(y) {
        var height;
        height = heightmapModel.get("worldTileHeight");
        return (y + height) % height;
      },
      calculateBackgroundPosition: function() {
        var buildingType, roadTileType, roadType, type;
        type = this.model.get("type");
        roadType = this.model.get("roadType");
        buildingType = this.model.get("buildingType");
        if (roadType !== 0) {
          roadTileType = this.calculateRoadTile();
          this.backgroundPositionX = 0 - roadTileType * 16;
          return this.backgroundPositionY = 0 - 256;
        } else if (buildingType !== 0) {
          this.backgroundPositionX = 0 - (buildingType - 1) * 16;
          return this.backgroundPositionY = 0 - 272;
        } else {
          this.backgroundPositionX = 0 - ((type % 16) * 16);
          return this.backgroundPositionY = 0 - (~~(type / 16) * 16);
        }
      },
      calculateRoadTile: function() {
        var a, b, c, d, e, heightmapData, n, s, t, w, x, y;
        x = this.model.get("x");
        y = this.model.get("y");
        heightmapData = heightmapModel.get("data");
        n = heightmapData[this.clampY(y - 1)][x].get("isOccupied");
        e = heightmapData[y][this.clampX(x + 1)].get("isOccupied");
        s = heightmapData[this.clampY(y + 1)][x].get("isOccupied");
        w = heightmapData[y][this.clampX(x - 1)].get("isOccupied");
        a = n << n * 4 - 4;
        b = e << e * 4 - 3;
        c = s << s * 4 - 2;
        d = w << w * 4 - 1;
        return t = a + b + c + d;
      },
      setListeners: function() {
        this.listenTo(this.model, "change:isOccupied", this.render);
        return this.listenTo(this.model, "neighborChanged", this.render);
      },
      setBackgroundPosition: function() {
        this.$el.css({
          backgroundPosition: "" + this.backgroundPositionX + "px " + this.backgroundPositionY + "px"
        });
        return this;
      }
    });
  });

}).call(this);
