// Generated by CoffeeScript 1.4.0
(function() {

  define(["views/viewport/Viewport", "models/Viewport", "Backbone"], function(ViewportView, viewportModel) {
    var AppView;
    return AppView = Backbone.View.extend({
      el: document,
      events: {
        "keydown": "onKeyDown"
      },
      initialize: function() {
        return new ViewportView;
      },
      onKeyDown: function(jqEvent) {
        var viewportX, viewportY, vx, vy;
        viewportX = viewportModel.get("x");
        viewportY = viewportModel.get("y");
        vx = 0;
        vy = 0;
        if (jqEvent.keyCode === 37) {
          vx -= 1;
        } else if (jqEvent.keyCode === 38) {
          vy -= 1;
        } else if (jqEvent.keyCode === 39) {
          vx += 1;
        } else if (jqEvent.keyCode === 40) {
          vy += 1;
        }
        viewportModel.set({
          x: viewportX + vx,
          y: viewportY + vy
        });
        if (!(vx === 0 && vy === 0)) {
          jqEvent.preventDefault();
          jqEvent.stopPropagation();
          return false;
        }
      }
    });
  });

}).call(this);
