// Generated by CoffeeScript 1.4.0
(function() {

  define(["views/viewport/Viewport", "models/Viewport", "views/toolbar/Toolbar", "Backbone"], function(ViewportView, viewportModel, ToolbarView) {
    var AppView;
    return AppView = Backbone.View.extend({
      el: document,
      initialize: function() {
        var toolbarView;
        toolbarView = new ToolbarView;
        return new ViewportView({
          toolbarView: toolbarView
        });
      }
    });
  });

}).call(this);
