// Generated by CoffeeScript 1.4.0
(function() {

  define(["views/buildings/Workable", "Backbone"], function(WorkableView) {
    var Factory;
    return Factory = WorkableView.extend({
      backgroundPositionX: -160,
      backgroundPositionY: -272
    });
  });

}).call(this);
