// Generated by CoffeeScript 1.4.0
(function() {

  define(["Backbone"], function() {
    var Farm;
    return Farm = Backbone.View.extend({
      backgroundPositionX: -32,
      backgroundPositionY: -272,
      initialize: function() {
        this.listenTo(this.model, "calculateBackgroundPosition", this.calculateBackgroundPosition);
        return this.calculateBackgroundPosition;
      },
      calculateBackgroundPosition: function() {
        return this.backgroundPositionX = 0 - 32 - (this.model.get("stage") * 16);
      },
      render: function() {}
    });
  });

}).call(this);
