// Generated by CoffeeScript 1.4.0
(function() {

  define(["Backbone"], function() {
    var Farm;
    return Farm = Backbone.View.extend({
      backgroundPositionX: -32,
      backgroundPositionY: -272,
      render: function() {}
    });
  });

}).call(this);
