// Generated by CoffeeScript 1.4.0
(function() {

  define(["Backbone"], function() {
    var Home;
    return Home = Backbone.View.extend({
      backgroundPositionX: 0,
      backgroundPositionY: -272,
      render: function() {}
    });
  });

}).call(this);
