// Generated by CoffeeScript 1.4.0
(function() {

  define(["views/buildings/Workable", "Backbone"], function(WorkableView) {
    var LumberMill;
    return LumberMill = WorkableView.extend({
      backgroundPositionX: -208,
      backgroundPositionY: -272
    });
  });

}).call(this);
