// Generated by CoffeeScript 1.4.0
(function() {

  define(["views/buildings/Workable", "Backbone"], function(WorkableView) {
    var Mine;
    return Mine = WorkableView.extend({
      backgroundPositionX: -16,
      backgroundPositionY: -272
    });
  });

}).call(this);
