// Generated by CoffeeScript 1.4.0
(function() {

  define(["views/buildings/Workable", "Backbone"], function(WorkableView) {
    var WaterWell;
    return WaterWell = WorkableView.extend({
      backgroundPositionX: -192,
      backgroundPositionY: -272
    });
  });

}).call(this);
