// Generated by CoffeeScript 1.4.0
(function() {

  define(["Backbone"], function() {
    var Building;
    return Building = Backbone.Model.extend({
      defaults: {
        needsWorker: false
      }
    });
  });

}).call(this);
