// Generated by CoffeeScript 1.4.0
(function() {

  define(["models/buildings/Building", "Backbone"], function(BuildingModel) {
    var Farm;
    return Farm = BuildingModel.extend({
      defaults: {
        needsWorker: true
      }
    });
  });

}).call(this);
