// Generated by CoffeeScript 1.4.0
(function() {

  define(["models/buildings/Building", "Backbone"], function(BuildingModel) {
    var Farm;
    return Farm = BuildingModel.extend({
      defaults: {
        needsWorker: true,
        stage: 0
      },
      initialize: function() {
        BuildingModel.prototype.initialize.call(this);
        return this.listenTo(this, "worked", this.onWorked);
      },
      onWorked: function() {
        this.set("stage", (this.get("stage") + 1) % 4);
        this.trigger("calculateBackgroundPosition");
        return this.get("tileModel").trigger("updateBackgroundPosition");
      }
    });
  });

}).call(this);
